Repository open-telemetry/opentelemetry-operator, pull requests merged in 2023-07, with the labels that each got.

#1850 [chore] Add functional test for OTLP metrics, traces collection and get the metrics,traces to supported Prometheus stack.
  CONTRIBUTING.md
  Makefile
  kuttl-test-openshift.yaml
  tests/e2e-openshift/otlp-metrics-traces/00-assert.yaml
  tests/e2e-openshift/otlp-metrics-traces/00-install-jaeger.yaml
  tests/e2e-openshift/otlp-metrics-traces/01-assert.yaml
  tests/e2e-openshift/otlp-metrics-traces/01-workload-monitoring.yaml
  tests/e2e-openshift/otlp-metrics-traces/02-assert.yaml
  tests/e2e-openshift/otlp-metrics-traces/02-otel-metrics-collector.yaml
  tests/e2e-openshift/otlp-metrics-traces/03-assert.yaml
  tests/e2e-openshift/otlp-metrics-traces/03-podmonitor.yaml
  tests/e2e-openshift/otlp-metrics-traces/04-assert.yaml
  tests/e2e-openshift/otlp-metrics-traces/04-metrics-traces-gen.yaml
  tests/e2e-openshift/otlp-metrics-traces/05-assert.yaml
  tests/e2e-openshift/otlp-metrics-traces/06-assert.yaml
  tests/e2e-openshift/otlp-metrics-traces/check_metrics.sh
  tests/e2e-openshift/otlp-metrics-traces/check_traces.sh
Labels: Skip Changelog

#1892 Fixed minimal target allocator example in readme
  README.md
Labels: Skip Changelog

#1894 Install golangci-lint in the local tools dir
  .github/workflows/continuous-integration.yaml
  Makefile
Labels: Skip Changelog, release-blocker

#1897 Prepare Release 0.81.0
  .chloggen/1823-new-catalog-source.yaml
  .chloggen/fix_sampler-type-required.yaml
  .chloggen/service-ports.yaml
  CHANGELOG.md
  README.md
  RELEASE.md
  bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml
  versions.txt
Labels: Skip Changelog

#1905 A fix for #1893 - ApacheModuleServiceNamespace falls back to instrumentation request namespace name or static default name
  .chloggen/fix-for-1893.yaml
  pkg/instrumentation/apachehttpd.go
  pkg/instrumentation/apachehttpd_test.go
  pkg/instrumentation/podmutator_test.go
  pkg/instrumentation/sdk_test.go
Labels: lgtm

#1875 adds envs handling to target allocator
  .chloggen/1773-targetallocator-env-handling.yaml
  apis/v1alpha1/opentelemetrycollector_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/opentelemetry.io_opentelemetrycollectors.yaml
  config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml
  docs/api.md
  pkg/targetallocator/container.go
  pkg/targetallocator/container_test.go
  tests/e2e/targetallocator-features/00-assert.yaml
  tests/e2e/targetallocator-features/00-install.yaml
Labels: lgtm

#1889 [target allocator] Restart target allocator when config changes
  .chloggen/feat_restart-targetallocator.yaml
  hack/modify-test-images.sh
  pkg/collector/reconcile/configmap.go
  pkg/collector/reconcile/configmap_test.go
  pkg/targetallocator/annotations.go
  pkg/targetallocator/annotations_test.go
  pkg/targetallocator/configmap.go
  pkg/targetallocator/configmap_test.go
  pkg/targetallocator/deployment.go
  pkg/targetallocator/deployment_test.go
  pkg/targetallocator/testdata/test.yaml
  tests/e2e/smoke-targetallocator/01-assert.yaml
  tests/e2e/smoke-targetallocator/01-change-ta-config.yaml
Labels: lgtm

#1910 [chore] Use KUBECONFIG env var to find the config for wait-until-hpa-ready
  tests/e2e-autoscale/autoscale/wait-until-hpa-ready.go
Labels: Skip Changelog

#1924 [target allocator] Fix Target Allocator config reload
  pkg/targetallocator/annotations.go
  pkg/targetallocator/annotations_test.go
  tests/e2e/smoke-targetallocator/00-assert.yaml
  tests/e2e/smoke-targetallocator/00-install.yaml
  tests/e2e/smoke-targetallocator/01-change-ta-config.yaml
Labels: area:target-allocator, Skip Changelog

#1937 [chore] Skip flaky test instrumentation-apache-multicontainer
  tests/e2e/instrumentation-apache-multicontainer/00-install-collector.yaml
  tests/e2e/instrumentation-apache-multicontainer/00-install-instrumentation.yaml
  tests/e2e/instrumentation-apache-multicontainer/01-assert.yaml
  tests/e2e/instrumentation-apache-multicontainer/01-install-app.yaml
  tests/e2e/instrumentation-apache-multicontainer/02-assert.yaml
  tests/e2e/instrumentation-apache-multicontainer/02-install-app.yaml
Labels: Skip Changelog

#1915 [autoinstrumentation] Bump go autoinstrumentation
  .chloggen/bump-go-instrumentation.yaml
  tests/e2e/instrumentation-go/02-assert.yaml
  versions.txt
Labels: ready-to-merge, lgtm

#1948 [chore] kube 1.27.4 version bumps
  cmd/operator-opamp-bridge/go.mod
  cmd/operator-opamp-bridge/go.sum
  cmd/otel-allocator/go.mod
  cmd/otel-allocator/go.sum
  go.mod
  go.sum
Labels: Skip Changelog

#1913 docs: add StatefulSet to Deployment modes
  README.md
Labels: Skip Changelog, needs-ok-to-test

#1958 Add version to the different feature flags
  pkg/featuregate/featuregate.go
Labels: Skip Changelog

#1966 Add Mikołaj Świątek as an approver
  .github/workflows/reusable-operator-hub-release.yaml
  README.md
  RELEASE.md
Labels: Skip Changelog
