Repository open-telemetry/opentelemetry-operator, pull requests merged in 2023-06, with the labels that each got.

#1792 Release 0.78
  .chloggen/1444-apache-httpd-final-v1.0.2.yaml
  .chloggen/1560-add-custom-metrics-support.yaml
  .chloggen/1777-override-label.yaml
  .chloggen/add-resources-requirements-target-allocator.yaml
  .chloggen/bump-oteljs-versions.yaml
  .chloggen/bump-python-version.yaml
  .chloggen/default_limits_for_go_init_container.yaml
  .chloggen/fix-go-release.yaml
  .chloggen/fix-pod-annotation-propagation.yaml
  .chloggen/fix_prometheus_relabel-configs.yaml
  .chloggen/fix_validate-ta-config.yaml
  CHANGELOG.md
  README.md
  RELEASE.md
  bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml
  versions.txt
Labels: Skip Changelog

#1795 Bump all the dependencies
  cmd/operator-opamp-bridge/go.mod
  cmd/operator-opamp-bridge/go.sum
  cmd/operator-opamp-bridge/metrics/reporter.go
  cmd/operator-opamp-bridge/operator/client.go
  cmd/otel-allocator/go.mod
  cmd/otel-allocator/go.sum
  cmd/otel-allocator/watcher/promOperator.go
  go.mod
  go.sum
  pkg/featuregate/featuregate_test.go
Labels: Skip Changelog

#1736 Add OTEL service version to sdk injection
  .chloggen/1736-add-service-version-injection.yaml
  pkg/instrumentation/sdk.go
  pkg/instrumentation/sdk_test.go
Labels: ready-to-merge

#1798 add prometheus metric exporter support for nodejs autoinstrumentation
  .chloggen/read_env_vars_for_nodejs_autoinstrumentation.yaml
  autoinstrumentation/nodejs/package.json
  autoinstrumentation/nodejs/src/autoinstrumentation.ts
  tests/e2e/instrumentation-nodejs/00-install-instrumentation.yaml
  tests/e2e/instrumentation-nodejs/01-assert.yaml
Labels: ready-to-merge

#1803 Fix version in status for OpenTelemetry Collector after upgrades
  .chloggen/collector-shown-version-is-incorrect-after-upgrade.yaml
  pkg/collector/upgrade/upgrade.go
  pkg/collector/upgrade/upgrade_test.go
Labels: ready-to-merge

#1829 Move Java agent auto-update to the operator repo
  .github/workflows/auto-update-java-agent.yaml
Labels: Skip Changelog

#1857 [autoinstrumentation/go] List permission requirements
  README.md
Labels: Skip Changelog

#1864 Explicitly set kind version when running tests in CI
  .github/workflows/e2e.yaml
  .github/workflows/scorecard.yaml
  hack/install-kuttl.sh
  kind-1.19.yaml
  kind-1.20.yaml
  kind-1.21.yaml
  kind-1.22.yaml
  kind-1.23.yaml
  kind-1.24.yaml
  kind-1.25.yaml
  kind-1.26.yaml
  kind-1.27.yaml
Labels: Skip Changelog, ready-to-merge

#1873 target-allocator : Fix typo in documentation
  cmd/otel-allocator/README.md
Labels: Skip Changelog, ready-to-merge

#1710 [target-allocator] Populate store assets (authorization information) for Prometheus CR watcher
  .chloggen/1710-prometheus-cr-scrape-config-credentials.yaml
  cmd/otel-allocator/README.md
  cmd/otel-allocator/main.go
  cmd/otel-allocator/watcher/file.go
  cmd/otel-allocator/watcher/promOperator.go
  cmd/otel-allocator/watcher/promOperator_test.go
  cmd/otel-allocator/watcher/watcher.go
Labels: ready-to-merge

#1860 Only admit configurations where Target Allocator has targets
  .chloggen/targetallocator-reject-no-targets.yaml
  apis/v1alpha1/opentelemetrycollector_webhook.go
  apis/v1alpha1/opentelemetrycollector_webhook_test.go
  pkg/targetallocator/adapters/config_to_prom_config.go
  pkg/targetallocator/adapters/config_to_prom_config_test.go
Labels: ready-to-merge

#1847 Fix for #1820 and #1821, unit tests
  .chloggen/1847-fix-issues-1820-1821.yaml
  pkg/instrumentation/apachehttpd.go
  pkg/instrumentation/apachehttpd_test.go
  pkg/instrumentation/podmutator_test.go
  pkg/instrumentation/sdk_test.go
Labels: ready-to-merge

#1650 feat: add skywalking parser to parse servicePort from config
  .chloggen/add-skywalking-parser.yaml
  pkg/collector/parser/receiver_skywalking.go
  pkg/collector/parser/receiver_skywalking_test.go
Labels: ready-to-merge

#1871 Prepare Release 0.80.0
  .chloggen/1684-init-containers.yaml
  .chloggen/1710-prometheus-cr-scrape-config-credentials.yaml
  .chloggen/1799-fix-crash-upgrading-collector-with-old-hpa.yaml
  .chloggen/1811-fix-empty-scrape-interval.yaml
  .chloggen/1826-apache-instr-unit-tests.yaml
  .chloggen/1827-apache-httpd-image-v-1-0-3.yaml
  .chloggen/1847-fix-issues-1820-1821.yaml
  .chloggen/1853-nginx-crd.yaml
  .chloggen/add-skywalking-parser.yaml
  .chloggen/bump-nodejs.yaml
  .chloggen/parentbased-jaeger-remote.yaml
  .chloggen/targetallocator-reject-no-targets.yaml
  .chloggen/update-operator-sdk128.yaml
  CHANGELOG.md
  README.md
  RELEASE.md
  bundle/manifests/opentelemetry-operator.clusterserviceversion.yaml
  versions.txt
Labels: Skip Changelog
