Repository open-telemetry/opentelemetry-operator, pull requests merged in 2024-08, with the labels that each got.

#3192 replace logging with debug in all tests
  tests/e2e-autoscale/autoscale/01-install.yaml
  tests/e2e-instrumentation/instrumentation-dotnet-musl/00-install-collector.yaml
  tests/e2e-instrumentation/instrumentation-nginx-contnr-secctx/00-install-collector.yaml
  tests/e2e-instrumentation/instrumentation-nginx-multicontainer/00-install-collector.yaml
  tests/e2e-instrumentation/instrumentation-nginx/00-install-collector.yaml
  tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/00-install-collector.yaml
  tests/e2e-multi-instrumentation/instrumentation-multi-no-containers/00-install-collector.yaml
  tests/e2e-multi-instrumentation/instrumentation-single-instr-first-container/00-install-collector.yaml
  tests/e2e-opampbridge/opampbridge/01-assert.yaml
  tests/e2e-opampbridge/opampbridge/01-install.yaml
  tests/e2e-pdb/pdb/00-install.yaml
  tests/e2e-pdb/target-allocator/00-install.yaml
  tests/e2e/smoke-dns-config/00-install.yaml
Labels: Skip Changelog

#3175 chore: update python auto-instrumentation dependencies 1.26.0/0.47b0
  autoinstrumentation/python/requirements.txt
Labels: Skip Changelog

#3202 Prepare release 0.106.0
  .chloggen/3189-openshift-dashboard-differentiate-otelcols.yaml
  .chloggen/3196-openshift-dashboard-list-wrong-namespaces.yaml
  .chloggen/fix-pdb-defaulting-logic.yaml
  .chloggen/fix-ta-with-proxy.yaml
  CHANGELOG.md
  README.md
  RELEASE.md
  bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml
  bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml
  versions.txt
Labels: Skip Changelog

#3221 Release 0.107.0
  .chloggen/3201-fix-labels-filter-arg.yaml
  .chloggen/extract-resources-ns.yaml
  CHANGELOG.md
  README.md
  RELEASE.md
  bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml
  bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml
  versions.txt
Labels: Skip Changelog

#3215 Refactor to use options correctly, remove duplication
  internal/components/component.go
  internal/components/exporters/helpers.go
  internal/components/generic_parser.go
  internal/components/generic_parser_test.go
  internal/components/multi_endpoint.go
  internal/components/nop_parser.go
  internal/components/receivers/helpers.go
  internal/components/receivers/scraper.go
  internal/components/single_endpoint.go
Labels: Skip Changelog

#3161 Propagate global scrape protocols by allowing for global config setting
  .chloggen/propagate-global-scrape-protocols.yaml
  apis/v1alpha1/targetallocator_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/opentelemetry.io_targetallocators.yaml
  internal/manifests/collector/targetallocator.go
  internal/manifests/collector/targetallocator_test.go
  internal/manifests/targetallocator/configmap.go
  internal/manifests/targetallocator/configmap_test.go
  tests/e2e/smoke-targetallocator/00-assert.yaml
  tests/e2e/smoke-targetallocator/00-install.yaml
  tests/e2e/smoke-targetallocator/chainsaw-test.yaml
Labels: area:collector, area:target-allocator

#3165 instrumentation/python: set OTEL_EXPORTER_OTLP_PROTOCOL to http/protobuf
  .chloggen/3165-python-otlp-protocol-env-var.yaml
  pkg/instrumentation/podmutator_test.go
  pkg/instrumentation/python.go
  pkg/instrumentation/python_test.go
  pkg/instrumentation/sdk_test.go
  tests/e2e-instrumentation/instrumentation-python-multicontainer/01-assert.yaml
  tests/e2e-instrumentation/instrumentation-python-multicontainer/02-assert.yaml
  tests/e2e-instrumentation/instrumentation-python/01-assert.yaml
  tests/e2e-multi-instrumentation/instrumentation-multi-multicontainer/01-assert.yaml
Labels: ready-to-merge

#3229 Bump prometheus-operator dependencies to 0.76.0
  cmd/otel-allocator/watcher/promOperator.go
  cmd/otel-allocator/watcher/promOperator_test.go
  go.mod
  go.sum
Labels: Skip Changelog

#3235 Update @swiatekm's affiliation in the README
  README.md
Labels: Skip Changelog

#3234 Bump k8s dependencies to 1.31.0
  Makefile
  bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml
  bundle/community/manifests/opentelemetry.io_instrumentations.yaml
  bundle/community/manifests/opentelemetry.io_opampbridges.yaml
  bundle/community/manifests/opentelemetry.io_opentelemetrycollectors.yaml
  bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml
  bundle/openshift/manifests/opentelemetry.io_instrumentations.yaml
  bundle/openshift/manifests/opentelemetry.io_opampbridges.yaml
  bundle/openshift/manifests/opentelemetry.io_opentelemetrycollectors.yaml
  config/crd/bases/opentelemetry.io_instrumentations.yaml
  config/crd/bases/opentelemetry.io_opampbridges.yaml
  config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml
  config/crd/bases/opentelemetry.io_targetallocators.yaml
  config/rbac/role.yaml
  docs/api.md
  go.mod
  go.sum
  tests/e2e/node-selector-collector/00-install-collectors-without-node-selector.yaml
  tests/e2e/node-selector-collector/chainsaw-test.yaml
Labels: Skip Changelog

#3120 App for TA collector mtls e2e tests
  .github/workflows/publish-test-e2e-images.yaml
  tests/test-e2e-apps/metrics-basic-auth/Dockerfile
  tests/test-e2e-apps/metrics-basic-auth/README.md
  tests/test-e2e-apps/metrics-basic-auth/app.py
  tests/test-e2e-apps/metrics-basic-auth/requirements.txt
Labels: Skip Changelog

#3245 link to offical docs page
  README.md
Labels: Skip Changelog

#3243 Move TA config parsing to configmap manifest builder
  internal/manifests/collector/targetallocator.go
  internal/manifests/collector/targetallocator_test.go
  internal/manifests/targetallocator/configmap.go
  internal/manifests/targetallocator/configmap_test.go
Labels: Skip Changelog
