Repository open-telemetry/opentelemetry-operator, pull requests merged in 2025-03, with the labels that each got.

#3761 [chore] fix Unsupported markdown Target Allocator
  cmd/otel-allocator/README.md
Labels: documentation, Skip Changelog

#3769 Fix renovate config for golangci-lint
  Makefile
Labels: Skip Changelog, internal

#3771 Fix renovate custom manager regex
  renovate.json
Labels: Skip Changelog

#3796 Bump golang x/oauth2 to fix CVE-2025-22868
  go.mod
  go.sum
Labels: Skip Changelog

#3803 cleanup: remove unused defaultAutoDetectFrequency variable
  internal/config/main.go
Labels: Skip Changelog

#3790 Refactor namespace selector handling in target allocator
  cmd/otel-allocator/internal/config/config.go
  cmd/otel-allocator/internal/config/config_test.go
  cmd/otel-allocator/internal/watcher/promOperator.go
  cmd/otel-allocator/internal/watcher/promOperator_test.go
Labels: Skip Changelog

#3777 Delay hashing scrape targets
  cmd/otel-allocator/benchmark_test.go
  cmd/otel-allocator/internal/allocation/allocator.go
  cmd/otel-allocator/internal/allocation/allocator_test.go
  cmd/otel-allocator/internal/allocation/least_weighted_test.go
  cmd/otel-allocator/internal/allocation/per_node_test.go
  cmd/otel-allocator/internal/allocation/strategy.go
  cmd/otel-allocator/internal/allocation/testutils.go
  cmd/otel-allocator/internal/prehook/prehook.go
  cmd/otel-allocator/internal/prehook/relabel.go
  cmd/otel-allocator/internal/prehook/relabel_test.go
  cmd/otel-allocator/internal/server/mocks_test.go
  cmd/otel-allocator/internal/server/server_test.go
  cmd/otel-allocator/internal/target/discovery.go
  cmd/otel-allocator/internal/target/discovery_test.go
  cmd/otel-allocator/internal/target/target.go
Labels: Skip Changelog

#3812 Comment out autoinstrumentation-php in versions.txt
  versions.txt
Labels: Skip Changelog

#3832 [target allocator] Use a uint64 hash instead of a string
  cmd/otel-allocator/internal/allocation/allocator.go
  cmd/otel-allocator/internal/allocation/strategy.go
  cmd/otel-allocator/internal/allocation/strategy_test.go
  cmd/otel-allocator/internal/diff/diff.go
  cmd/otel-allocator/internal/diff/diff_test.go
  cmd/otel-allocator/internal/server/mocks_test.go
  cmd/otel-allocator/internal/server/server_test.go
  cmd/otel-allocator/internal/target/target.go
Labels: area:target-allocator, Skip Changelog

#3841 Add GOTEST_OPTS for unit tests
  Makefile
Labels: Skip Changelog

#3842 [target allocator] Use ScratchBuilder for building targets
  cmd/otel-allocator/internal/target/discovery.go
Labels: area:target-allocator, Skip Changelog

#3853 Fix a few typos.
  README.md
  docs/compatibility.md
Labels: Skip Changelog

#3854 Docs: Update Allocator Docs to include Selectors
  cmd/otel-allocator/README.md
Labels: Skip Changelog
