Repository open-telemetry/opentelemetry-operator, pull requests merged in 2025-05, with the labels that each got.

#3976 [targetallocator] collector namespace overridden by env var
  .chloggen/override_with_env.yaml
  cmd/otel-allocator/internal/config/config.go
  cmd/otel-allocator/internal/config/config_test.go
Labels: ready-to-merge

#3830 [docs] Add RFC for managed CR
  docs/rfcs/managed.md
Labels: Skip Changelog, ready-to-merge

#3978 Prepare release 0.125.0
  .chloggen/3950.yaml
  .chloggen/3963.yaml
  .chloggen/fix_opamp-cmdline-values.yaml
  .chloggen/fix_ta-cmdline-values.yaml
  .chloggen/keep_going_if_collector_crd_is_not_present.yaml
  .chloggen/nikola-jokic_fix-status-replicas.yaml
  .chloggen/ocpdashboards.yaml
  .chloggen/override_with_env.yaml
  CHANGELOG.md
  RELEASE.md
  bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml
  bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml
  docs/compatibility.md
  versions.txt
Labels: Skip Changelog

#3999 Bump chloggen to latest v0.23.1
  Makefile
Labels: Skip Changelog

#4012 [target allocator] Fix user-defined volumes
  .chloggen/fix_ta-volume.yaml
  internal/manifests/targetallocator/volume.go
  internal/manifests/targetallocator/volume_test.go
  tests/e2e-targetallocator-cr/01-assert.yaml
  tests/e2e-targetallocator-cr/01-install.yaml
Labels: area:target-allocator

#4021 prepare release v0.126.0
  .chloggen/allow-config.yaml
  .chloggen/bug-fix-3996.yaml
  .chloggen/ct_update-default-grace-period-to-30s.yaml
  .chloggen/fix-3872.yaml
  .chloggen/fix_ta-volume.yaml
  .chloggen/terminationGracePeriodSeconds-apply-to-daemonset.yaml
  CHANGELOG.md
  RELEASE.md
  bundle/community/manifests/opentelemetry-operator.clusterserviceversion.yaml
  bundle/openshift/manifests/opentelemetry-operator.clusterserviceversion.yaml
  docs/compatibility.md
  versions.txt
Labels: Skip Changelog

#4023 Fix TargetAllocatorList definition
  apis/v1alpha1/targetallocator_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
Labels: Skip Changelog

#4024 [opamp] Add README for OpAMP Bridge
  cmd/operator-opamp-bridge/README.md
Labels: Skip Changelog, area:opamp

#4039 [chore] Add stop-kind make target to delete the cluster created by start-kind
  CONTRIBUTING.md
  Makefile
Labels: Skip Changelog

#4046 [internal/config] remove all getters
  apis/v1alpha1/instrumentation_webhook.go
  internal/config/config.go
  internal/config/config_test.go
  internal/controllers/opentelemetrycollector_controller.go
  internal/controllers/targetallocator_controller.go
  internal/manifests/collector/collector.go
  internal/manifests/collector/configmap.go
  internal/manifests/collector/container.go
  internal/manifests/collector/daemonset.go
  internal/manifests/collector/deployment.go
  internal/manifests/collector/horizontalpodautoscaler.go
  internal/manifests/collector/ingress.go
  internal/manifests/collector/poddisruptionbudget.go
  internal/manifests/collector/podmonitor.go
  internal/manifests/collector/rbac.go
  internal/manifests/collector/route.go
  internal/manifests/collector/service.go
  internal/manifests/collector/service_test.go
  internal/manifests/collector/serviceaccount.go
  internal/manifests/collector/servicemonitor.go
  internal/manifests/collector/statefulset.go
  internal/manifests/collector/volume.go
  internal/manifests/opampbridge/container.go
  internal/manifests/opampbridge/deployment.go
  internal/manifests/opampbridge/volume.go
  internal/manifests/targetallocator/configmap.go
  internal/manifests/targetallocator/container.go
  internal/manifests/targetallocator/deployment.go
  internal/manifests/targetallocator/poddisruptionbudget.go
  internal/manifests/targetallocator/service.go
  internal/manifests/targetallocator/targetallocator.go
  internal/manifests/targetallocator/volume.go
  main.go
  pkg/instrumentation/golang.go
  pkg/instrumentation/podmutator.go
  pkg/instrumentation/upgrade/upgrade.go
Labels: Skip Changelog
